config/routes.rb
Rails.application.routes.draw do

  resources :fishers
  resources :devices
  resources :device_uploads, controller: "device_upload"
  resources :location_search, controller: "location_search"

  namespace :api do
    resources :device_uploads, controller: "device_upload"
  end

  namespace :admin do
    resources :access_requests, only: %w(index show update)
    resources :users, only: %w(index update)
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  resource :dashboard, only: :show, controller: "dashboard"

  # for when users inevitably refresh the registration page
  get '/users', to: redirect("/users/sign_up")
  get '/thanks', to: "thanks#show"

  root to: "landing#show"
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @fishers = Fisher.includes(:devices).all
    @devices = Device.includes(:fisher)

    if current_user_fisher?
      @devices = @devices.where(fisher: current_user)
    end

    @devices = @devices.all
  end
end

app/views/dashboard/index.html.erb
<div class="container-lg mt-4">
  <div class="col-12">
    <h2>Smelts Dashboard</h2>

  </div>
</div>

<div class="container-lg mt-4 d-flex">
  <div class="col-6">
    <div class="Box">
      <div class="Box-header">
        <h3 class="Box-title">
          Fishers
        </h3>
      </div>
      <ul>
        <% @fishers.each do |fisher| %>
          <li class="Box-row d-flex flex-items-center">
            <div class="flex-auto">
              <strong><%= fisher.name %></strong>
              <div class="text-small text-gray-light">
                <%= pluralize(fisher.devices.unique.count, "device") %>
              </div>
            </div>
            <%= link_to "View", fisher_path(fisher), class: "btn btn-primary" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/dashboard/show.html.erb
<div class="container-lg mt-4">
  <div class="col-12">
    <h2>Smelts Dashboard</h2>

  </div>
</div>

<div class="container-lg mt-4 d-flex">
  <div class="col-12">
    <% if current_user_fisher? %>
      <div class="Box">
        <div class="Box-header">
          <h3 class="Box-title">
            Your Devices (<%= @devices.count %>)
          </h3>
        </div>
        <div class="col-12">
          <div class="d-flex">
            <p class="p-1 flex-1">Device ID</p>
            <p class="p-1 flex-1">Location</p>
            <p class="p-1 flex-1">Date of Set</p>
            <p class="p-1 flex-1">Date of Retrieval</p>
          </div>
          <% if @devices.any? %>
            <% @devices.each do |device| %>
              <div class="d-flex">
                <div class="p-1 flex-1"><%= device.modem_id %></div>
                <div class="p-1 flex-1"><%= device.geom.latitude %>, <%= device.geom.longitude %></div>
                <div class="p-1 flex-1">N/A</div>
                <div class="p-1 flex-1">N/A</div>
              </div>
            <% end %>
          <% else %>
            <div class="d-flex">
              <p class="p-1 flex-1">You have no devices.</p>
            </div>
          <% end %>
        </div>
      </div>
    <% else %>
      <% # admin or agency user %>
      <div class="Box">
        <div class="Box-header">
          <h3 class="Box-title">
            Fishers
          </h3>
        </div>
        <ul>
          <% @fishers.each do |fisher| %>
            <li class="Box-row d-flex flex-items-center">
              <div class="flex-auto">
                <strong><%= fisher.full_name %></strong>
                <div class="text-small text-gray-light">
                  <%= pluralize(fisher.devices.unique.count, "device") %>
                </div>
              </div>
              <%= link_to "View", fisher_path(fisher), class: "btn btn-primary" %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</div>