config/routes.rb
Rails.application.routes.draw do

  resources :fishers
  resources :devices
  resources :device_uploads, controller: "device_upload"
  resources :location_search, controller: "location_search"

  namespace :api do
    resources :device_uploads, controller: "device_upload"
  end

  namespace :admin do
    resources :access_requests, only: %w(index show update)
    resources :users, only: %w(index update)
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  resource :dashboard, only: :show, controller: "dashboard"

  # for when users inevitably refresh the registration page
  get '/users', to: redirect("/users/sign_up")
  get '/thanks', to: "thanks#show"

  root to: "landing#show"
end

app/views/shared/_admin_nav.html.erb
<div class="container-lg">
  <div class="Header color-bg-pantone col-12">
    <div class="Header-item">
      <%= link_to root_path, class: "Header-link f4 d-flex flex-items-center" do %>
        <%= image_tag "smelts-logo.png", class: "mr-2" %>
        <span class="text-uppercase">Seacloud</span>
      <% end %>
    </div>
    <div class="Header-item">
      <input type="search" class="form-control input-dark" placeholder="permit number" />
    </div>
    <div class="Header-item">
      <%= octicon("person") %>
      <%= link_to("User Management", admin_users_url, class: "ml-2 Header-link") %>
    </div>
    <div class="Header-item">
      <%= octicon("check") %>
      <%= link_to("Access Requests", admin_access_requests_url, class: "ml-2 Header-link") %>
      <% if User.outstanding_access_requests.any? %>
        <span class="Counter ml-2"><%= User.outstanding_access_requests.count %></span>
      <% end %>
    </div>
    <div class="Header-item">
      <%= octicon("list-unordered") %>
      <%= link_to("Device File Uploads", device_uploads_path, class: "ml-2 Header-link") %>
    </div>
    <div class="Header-item">
      <%= octicon("file") %>
      <%= link_to("Upload Device File", new_device_upload_path, class: "ml-2 Header-link") %>
    </div>
    <div class="Header-item Header-item--full">
      <%= octicon("search") %>
      <%= link_to("Location Search", location_search_index_path, class: "ml-2 Header-link") %>
    </div>
    <div class="Header-item mr-0">
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
    </div>
  </div>
</div>

app/views/shared/_fisher_nav.html.erb
<div class="container-lg">
  <div class="Header color-bg-pantone col-12">
    <div class="Header-item">
      <%= link_to root_path, class: "Header-link f4 d-flex flex-items-center" do %>
        <%= image_tag "smelts-logo.png", class: "mr-2" %>
        <span class="text-uppercase">Seacloud</span>
      <% end %>
    </div>
    <div class="Header-item Header-item--full">
    </div>
    <div class="Header-item">
      <%= link_to(new_device_upload_path, class: "ml-2 btn") do %>
        <%= octicon("upload") %> Upload Device File
      <% end %>
    </div>
    <div class="Header-item mr-0">
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
    </div>
  </div>
</div>

app/views/shared/_signed_out.html.erb
<div class="container-lg">
  <div class="Header color-bg-pantone col-12">
    <div class="Header-item">
      <%= link_to root_path, class: "Header-link f4 d-flex flex-items-center" do %>
        <%= image_tag "smelts-logo.png", class: "mr-2" %>
        <span class="text-uppercase">Seacloud</span>
      <% end %>
    </div>
    <% unless devise_controller? %>
      <div class="Header-item Header-item--full"></div>
      <div class="Header-item">
        <div class="container-lg mt-4">
          <% user = User.new %>
          <%= form_for(user, as: user, url: session_path(user)) do |f| %>
            <%= f.email_field :email, autocomplete: "email", class: "form-control", placeholder: "email address" %>
            <%= f.password_field :password, class: "form-control", placeholder: "password" %>
            <%= f.submit "Log in", class: "btn" %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>