config/routes.rb
Rails.application.routes.draw do

  resources :fishers
  resources :devices
  resources :device_uploads, controller: "device_upload"
  resources :location_search, controller: "location_search"

  namespace :api do
    resources :device_uploads, controller: "device_upload"
  end

  namespace :admin do
    resources :access_requests, only: %w(index show update)
    resources :users, only: %w(index update)
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  resource :dashboard, only: :show, controller: "dashboard"

  # for when users inevitably refresh the registration page
  get '/users', to: redirect("/users/sign_up")
  get '/thanks', to: "thanks#show"

  root to: "landing#show"
end

app/controllers/access_requests_controller.rb
class AccessRequestsController < ApplicationController

  before_action :require_admin_user

  def index
    @access_requests = User.outstanding_access_requests.paginate(page: params[:page])
  end

  def show
  end

  def update
    user = User.find(params[:id])

    if user.update(update_params)
      if user.active?
        flash[:success] = "Access request approved."
        AccessRequestsMailer.approved_email(user).deliver_now
      else
        flash[:success] = "Access request rejected."
        AccessRequestsMailer.rejected_email(user).deliver_now
      end
    else
      flash[:error] = "Unknown option passed, please approve or reject the access request."
    end

    redirect_to access_requests_url
  end

  private

  def update_params
    params.require(:user).permit(:status)
  end
end

app/controllers/admin/access_requests_controller.rb
class Admin::AccessRequestsController < AdminController

  before_action :require_admin_user

  def index
    @access_requests = User.outstanding_access_requests.paginate(page: params[:page])
  end

  def show
  end

  def update
    user = User.find(params[:id])

    if user.update(update_params)
      if user.active?
        flash[:success] = "Access request approved."
        AccessRequestsMailer.approved_email(user).deliver_now
      else
        flash[:success] = "Access request rejected."
        AccessRequestsMailer.rejected_email(user).deliver_now
      end
    else
      flash[:error] = "Unknown option passed, please approve or reject the access request."
    end

    redirect_to admin_access_requests_url
  end

  private

  def update_params
    params.require(:user).permit(:status)
  end
end

app/views/admin/access_requests/index.html.erb
<div class="container-lg mt-4">
  <div class="col-12">
    <h2>Access Requests</h2>
  </div>
</div>

<div class="container-lg mt-4 d-flex">
  <div class="col-12">
    <div class="Box">
      <% if @access_requests.none? %>
        <div class="blankslate">
          <h3 class="mb-1">There are no outstanding access requests.</h3>
          <p>Enjoy your day!</p>
        </div>
      <% else %>
        <div class="Box-header">
          <h3 class="Box-title">
            The following users are requesting access
          </h3>
        </div>
        <div class="Box-body">
        <table class="width-full">
          <thead>
          <tr class="border-bottom">
            <th>Full Name</th>
            <th>Access Needed</th>
            <th>E-mail address</th>
            <th>Permit Number</th>
            <th></th>
          </tr>
          </thead>
          <tbody>
          <% @access_requests.each do |user| %>
            <tr class="border-bottom">
              <td class="p-2 css-truncate css-truncate-overflow" style="width: 200px;" title="<%= user.full_name %>">
                <strong><%= user.full_name %></strong>
              </td>
              <td class="p-2">
                <%= user.class.name.titleize %>
              </td>
              <td class="p-2">
                <%= user.email %>
              </td>
              <td class="p-2">
                <% if user.is_a?(Fisher) %>
                  <%= user.permit_number %>
                <% else %>
                  N/A
                <% end %>
              </td>
              <td class="p-2">
                <div class="mr-2">
                  <%= form_for user, url: admin_access_request_path(user), html: {class: "d-inline-block"} do |f| %>
                    <%= hidden_field_tag("user[status]", :active) %>
                    <%= f.button class: "btn btn-sm btn-primary" do %>
                      <%= octicon "zap" %>
                      Approve
                    <% end %>
                  <% end %>
                  <%= form_for user, url: admin_access_request_path(user), html: {class: "d-inline-block"} do |f| %>
                    <%= hidden_field_tag("user[status]", :rejected) %>
                    <%= f.button class: "btn btn-sm btn-danger" do %>
                      <%= octicon "trash" %>
                      Reject
                    <% end %>
                  <% end %>
                </div>
              </td>
            </tr>
          <% end %>
          </tbody>
          <% if @access_requests.total_pages > 1 %>
            <tfoot>
            <tr>
              <td colspan="5">
                <%= will_paginate @access_requests, previous_label: "Previous", next_label: "Next" %>
              </td>
            </tr>
            </tfoot>
          <% end %>
        </table>
      </div>
      <% end  %>
    </div>
  </div>
</div>