config/routes.rb
Rails.application.routes.draw do

  resources :fishers
  resources :devices
  resources :device_uploads, controller: "device_upload"
  resources :location_search, controller: "location_search"

  namespace :api do
    resources :device_uploads, controller: "device_upload"
  end

  namespace :admin do
    resources :access_requests, only: %w(index show update)
    resources :users, only: %w(index update)
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  resource :dashboard, only: :show, controller: "dashboard"

  # for when users inevitably refresh the registration page
  get '/users', to: redirect("/users/sign_up")
  get '/thanks', to: "thanks#show"

  root to: "landing#show"
end

app/models/fisher.rb
class Fisher < User
  validates :permit_number, :address, :city, :state, :zip_code, :phone_number, presence: true

  has_many :devices
  has_many :device_uploads, inverse_of: :fisher

  after_initialize :set_access_needed

  def set_access_needed
    @access_needed = "Fisher"
  end
end

app/controllers/fishers_controller.rb
class FishersController < ApplicationController
  def show
    @fisher = Fisher.includes(:devices).find(params[:id])
  end
end

app/views/fishers/show.html.erb
<div class="container-lg mt-4">
  <div class="col-12">
    <nav aria-label="Breadcrumb" class="mb-2">
      <ol>
        <li class="breadcrumb-item">
          <%= link_to "Dashboard", root_path %>
        </li>
        <li class="breadcrumb-item" aria-current="page"><%= @fisher.full_name %></li>
      </ol>
    </nav>
  </div>
</div>
<div class="container-lg mt-4">
  <div class="col-12">
    <div class="Box">
      <div class="Box-header">
        <h3 class="Box-title">
          Devices
        </h3>
      </div>
      <ul>
        <% @fisher.devices.unique.order(:modem_id).each do |device| %>
          <li class="Box-row d-flex flex-items-center">
            <div class="flex-auto">
              <div class="text-small text-gray-light">
                <p class="mb-0"><strong>Modem ID</strong>: <%= device.modem_id %> <%= link_to "(View Device Events)", device_path(device) %></p>
                <p class="mb-0"><strong>Device Event time</strong>: <%= device.dt %></p>
                <p class="mb-0"><strong>Event Type</strong>: <%= device.event_type %></p>
                <p class="mb-0"><strong>Latitude</strong>: <%= device.geom.latitude %></p>
                <p class="mb-0"><strong>Longitude</strong>: <%= device.geom.longitude %></p>
                <%= link_to "(Search Location)", location_search_index_path(latitude: device.geom.latitude, longitude: device.geom.longitude, radius: 1) %>
                <% if device.depth %>
                  <p class="mb-0"><strong>Depth</strong>: <%= device.depth || "N/A" %></p>
                <% end %>
                <% if device.altitude %>
                  <p class="mb-0"><strong>Altitude</strong>: <%= device.altitude || "N/A" %></p>
                <% end %>
                <p class="mb-0"><strong>Upload time</strong>: <%= time_ago_in_words(device.created_at) %> ago</p>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>